dist: xenial
language: node_js
node_js:
- node
- 9.11.1
before_install:
- openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
deploy:
   provider: gae
   keyfile: service-account.json
   project: ri-app

