dist: xenial
language: node_js
node_js:
- node
- 9.11.1
before_install:
- openssl aes-256-cbc -K $encrypted_1b88abad10de_key -iv $encrypted_1b88abad10de_iv -in client-secret.json.enc -out client-secret.json -d
deploy:
   provider: gae
   keyfile: client-secret.json
   project: ri-app-1

